source "https://rubygems.org"

gem "lita", "~> 4.7"
gem "lita-slack"
gem "lita-google-images"
gem "lita-animate"
gem "lita-karma"
gem "lita-wikipedia"
gem "lita-markov"
gem "lita-regexcellent"
gem "lita-heroku-keepalive"
